### ISSUE TITLE
Issue with Exporting String.prototype Methods in Node.js

### ISSUE THREAD

**Issue by wozandy05** [Tulip-0333/python.js#1]
Hello, @Tulip-0333. If I run in the node.js environment and I use the require statement to export, it shows that reverse is not defined. Later I found that there is no need to export reverse in module.exports because if you export it in String A method is added to .prototype, such as reverse, and you want to export this method through module.exports. It should be noted that the method on String.prototype is global. Once added, all string instances can access this method. So there is no need to export it anymore unless you name it as a new function as a separate module, and the input statement is not right. I didn’t input it, so it just printed out the subsequent output, and then asked me to do it again. Enter, request enhancements and features.

**Comment by Tulip-0333** [comment]
Fixed. Sorry for the latency.
